from enum import Enum


class AnimationId(Enum):

    SORTING_OBJECT_FADE_IN = "SORTING_OBJECT_FADE_IN"
    SORTING_OBJECT_FADE_OUT = "SORTING_OBJECT_FADE_OUT"
    SORTING_OBJECT_BAR_EXCHANGE = "SORTING_OBJECT_BAR_EXCHANGE"
    SORTING_OBJECT_FOCUS = "SORTING_OBJECT_FOCUS"
    SORTING_OBJECT_SELECT = "SORTING_OBJECT_SELECT"
    SORTING_OBJECT_SHIFT = "SORTING_OBJECT_SHIFT"
    BAR_FILL = "BAR_FILL"
    BAR_STROKE = "BAR_STROKE"
    BAR_SELECT = "BAR_SELECT"
    BAR_FOCUS = "BAR_FOCUS"
    BAR_DESELECT = "BAR_DESELECT"
    BAR_WIGGLE = "BAR_WIGGLE"
    BAR_DISAPPEAR = "BAR_DISAPPEAR"
    BAR_MOVE = "BAR_MOVE"
    BAR_REAPPEAR = "BAR_REAPPEAR"
    CIRCLE_FADE_IN = "CIRCLE_FADE_IN"
    CIRCLE_FADE_OUT = "CIRCLE_FADE_OUT"
    CIRCLE_SELECT = "CIRCLE_SELECT"
    CIRCLE_MOVE = "CIRCLE_MOVE"
